var openhtml='';
var topopenhtml='';
openhtml+= ' <div id="kful">';
openhtml+= ' <div class="li h">';
openhtml+= '  <span class="time">开服时间</span>';
openhtml+= '  <span class="name">游戏名称</span>';
openhtml+= '  <span class="server">服务器</span>';
openhtml+= '  <span class="status">状态</span>';
openhtml+= '  <span class="gift">礼包</span>';
openhtml+= '</div>';
								openhtml+= '<div id="_potint_server_1" style="display:block;">';
							topopenhtml= '<div id="kflbt">';
			topopenhtml+= '    <div class="pic"><a href="http://www.97time.com/wz/" target="_blank"><img src="http://www.97time.com/images/lgame/img_wz.jpg" width="95" height="60" /></a></div>';
			topopenhtml+= '      <div class="r">';
			topopenhtml+= '    <div class="title" id="topgamename"><a href="http://www.97time.com/wz/" target="_blank">武尊</a></div>';
							topopenhtml+= '    <div class="time" id="topopendate" data-value="02-10 12:00">今天 12:00</div>';
						topopenhtml+= '      <div class="fu" id="toplink"><a href="http://www.97time.com/users/gamelogin.php?game=6&server=488" rel="nofollow" target="_blank" >S488服</a>　　<a class="lb" href="http://www.97time.com/wz/xsk.html" target="_blank" rel="nofollow">领取礼包</a></div>';
			topopenhtml+= '    </div>';
			topopenhtml+= '  <div class="clear"></div>';
			topopenhtml+= '</div>';
							openhtml += '  <div class="li"  data-value="1423540800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=6&server=488" target="_blank" title="97time武尊" style="display:block;"  openurl="/users/gamelogin.php?game=6&server=488" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_1" data-value="02-10 12:00">今天 12:00</span>';
				openhtml += '      <span class="name">武尊</span>';
		openhtml += '      <span class="server">S488</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://www.97time.com/wz/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423537200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=154" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=154" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_2" data-value="02-10 11:00">今天 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S154</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423533600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=24&server=12" target="_blank" title="97time战天" style="display:block;"  openurl="/users/gamelogin.php?game=24&server=12" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_3" data-value="02-10 10:00">今天 10:00</span>';
				openhtml += '      <span class="name">战天</span>';
		openhtml += '      <span class="server">S12</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zt.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423533600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=18&server=86" target="_blank" title="97time魔龙诀" style="display:block;"  openurl="/users/gamelogin.php?game=18&server=86" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_4" data-value="02-10 10:00">今天 10:00</span>';
				openhtml += '      <span class="name">魔龙诀</span>';
		openhtml += '      <span class="server">S86</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mlj.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423533600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=15&server=331" target="_blank" title="97time风云无双" style="display:block;"  openurl="/users/gamelogin.php?game=15&server=331" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_5" data-value="02-10 10:00">今天 10:00</span>';
				openhtml += '      <span class="name">风云无双</span>';
		openhtml += '      <span class="server">S331</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://fy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423533600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=26&server=13" target="_blank" title="97time霸者之刃" style="display:block;"  openurl="/users/gamelogin.php?game=26&server=13" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_6" data-value="02-10 10:00">今天 10:00</span>';
				openhtml += '      <span class="name">霸者之刃</span>';
		openhtml += '      <span class="server">S13</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://bz.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423530000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=339" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=339" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_7" data-value="02-10 09:00">今天 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S339</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423530000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1055" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1055" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_8" data-value="02-10 09:00">今天 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1055</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423472400">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=153" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=153" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_9" data-value="02-09 17:00">02-09 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S153</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423450800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=152" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=152" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_10" data-value="02-09 11:00">02-09 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S152</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423443600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=338" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=338" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_11" data-value="02-09 09:00">02-09 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S338</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423443600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1054" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1054" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_12" data-value="02-09 09:00">02-09 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1054</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423386000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=151" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=151" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_13" data-value="02-08 17:00">02-08 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S151</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
				openhtml+= '</div><div id="_potint_server_2" style="display:none; _margin-top:-10px;">';
															openhtml += '  <div class="li"  data-value="1423364400">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=150" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=150" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_14" data-value="02-08 11:00">02-08 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S150</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423360800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=26&server=12" target="_blank" title="97time霸者之刃" style="display:block;"  openurl="/users/gamelogin.php?game=26&server=12" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_15" data-value="02-08 10:00">02-08 10:00</span>';
				openhtml += '      <span class="name">霸者之刃</span>';
		openhtml += '      <span class="server">S12</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://bz.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423357200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=337" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=337" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_16" data-value="02-08 09:00">02-08 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S337</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423357200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1053" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1053" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_17" data-value="02-08 09:00">02-08 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1053</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423299600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=149" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=149" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_18" data-value="02-07 17:00">02-07 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S149</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423278000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=148" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=148" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_19" data-value="02-07 11:00">02-07 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S148</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423270800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=336" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=336" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_20" data-value="02-07 09:00">02-07 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S336</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423270800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1052" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1052" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_21" data-value="02-07 09:00">02-07 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1052</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423213200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=147" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=147" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_22" data-value="02-06 17:00">02-06 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S147</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423202400">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=13&server=150" target="_blank" title="97time赤月传说" style="display:block;"  openurl="/users/gamelogin.php?game=13&server=150" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_23" data-value="02-06 14:00">02-06 14:00</span>';
				openhtml += '      <span class="name">赤月传说</span>';
		openhtml += '      <span class="server">S150</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://cycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423195200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=6&server=487" target="_blank" title="97time武尊" style="display:block;"  openurl="/users/gamelogin.php?game=6&server=487" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_24" data-value="02-06 12:00">02-06 12:00</span>';
				openhtml += '      <span class="name">武尊</span>';
		openhtml += '      <span class="server">S487</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://www.97time.com/wz/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423191600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=146" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=146" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_25" data-value="02-06 11:00">02-06 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S146</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423188000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=15&server=330" target="_blank" title="97time风云无双" style="display:block;"  openurl="/users/gamelogin.php?game=15&server=330" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_26" data-value="02-06 10:00">02-06 10:00</span>';
				openhtml += '      <span class="name">风云无双</span>';
		openhtml += '      <span class="server">S330</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://fy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
				openhtml+= '</div><div id="_potint_server_3" style="display:none; _margin-top:-10px;">';
															openhtml += '  <div class="li"  data-value="1423188000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=24&server=11" target="_blank" title="97time战天" style="display:block;"  openurl="/users/gamelogin.php?game=24&server=11" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_27" data-value="02-06 10:00">02-06 10:00</span>';
				openhtml += '      <span class="name">战天</span>';
		openhtml += '      <span class="server">S11</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zt.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423188000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=18&server=85" target="_blank" title="97time魔龙诀" style="display:block;"  openurl="/users/gamelogin.php?game=18&server=85" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_28" data-value="02-06 10:00">02-06 10:00</span>';
				openhtml += '      <span class="name">魔龙诀</span>';
		openhtml += '      <span class="server">S85</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mlj.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423188000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=26&server=11" target="_blank" title="97time霸者之刃" style="display:block;"  openurl="/users/gamelogin.php?game=26&server=11" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_29" data-value="02-06 10:00">02-06 10:00</span>';
				openhtml += '      <span class="name">霸者之刃</span>';
		openhtml += '      <span class="server">S11</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://bz.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423184400">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=335" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=335" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_30" data-value="02-06 09:00">02-06 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S335</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423184400">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1051" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1051" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_31" data-value="02-06 09:00">02-06 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1051</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423126800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=145" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=145" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_32" data-value="02-05 17:00">02-05 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S145</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423116000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=3&server=57" target="_blank" title="97time烈火战神" style="display:block;"  openurl="/users/gamelogin.php?game=3&server=57" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_33" data-value="02-05 14:00">02-05 14:00</span>';
				openhtml += '      <span class="name">烈火战神</span>';
		openhtml += '      <span class="server">S57</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://www.97time.com/lhzs/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423105200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=144" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=144" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_34" data-value="02-05 11:00">02-05 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S144</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423098000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=334" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=334" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_35" data-value="02-05 09:00">02-05 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S334</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423098000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1050" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1050" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_36" data-value="02-05 09:00">02-05 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1050</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423040400">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=143" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=143" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_37" data-value="02-04 17:00">02-04 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S143</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423018800">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=142" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=142" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_38" data-value="02-04 11:00">02-04 11:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S142</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423015200">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=26&server=10" target="_blank" title="97time霸者之刃" style="display:block;"  openurl="/users/gamelogin.php?game=26&server=10" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_39" data-value="02-04 10:00">02-04 10:00</span>';
				openhtml += '      <span class="name">霸者之刃</span>';
		openhtml += '      <span class="server">S10</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://bz.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
				openhtml+= '</div><div id="_potint_server_4" style="display:none; _margin-top:-10px;">';
															openhtml += '  <div class="li"  data-value="1423011600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=19&server=333" target="_blank" title="97time斩龙传奇" style="display:block;"  openurl="/users/gamelogin.php?game=19&server=333" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_40" data-value="02-04 09:00">02-04 09:00</span>';
				openhtml += '      <span class="name">斩龙传奇</span>';
		openhtml += '      <span class="server">S333</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://zlcq.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1423011600">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=8&server=1049" target="_blank" title="97time武易" style="display:block;"  openurl="/users/gamelogin.php?game=8&server=1049" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_41" data-value="02-04 09:00">02-04 09:00</span>';
				openhtml += '      <span class="name">武易</span>';
		openhtml += '      <span class="server">S1049</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://wy.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1422954000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=20&server=141" target="_blank" title="97time魅影传说" style="display:block;"  openurl="/users/gamelogin.php?game=20&server=141" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_42" data-value="02-03 17:00">02-03 17:00</span>';
				openhtml += '      <span class="name">魅影传说</span>';
		openhtml += '      <span class="server">S141</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://mycs.97time.com/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
														openhtml += '  <div class="li"  data-value="1422936000">';
		openhtml += '    	<a href="http://www.97time.com/users/gamelogin.php?game=6&server=486" target="_blank" title="97time武尊" style="display:block;"  openurl="/users/gamelogin.php?game=6&server=486" rel="nofollow">';
					openhtml += '      <span class="time" id="today_opt_43" data-value="02-03 12:00">02-03 12:00</span>';
				openhtml += '      <span class="name">武尊</span>';
		openhtml += '      <span class="server">S486</span>';
		openhtml += '      <span class="status">火爆</span>';
		openhtml += '      <span class="gift" title="礼包"></span>';
		openhtml += '      </a><a class="libao" href="http://www.97time.com/wz/xsk.html" target="_blank" rel="nofollow"></a>';
		openhtml += '  </div>';
			openhtml+= '</div></ul>';
$('#left_game_list').html(topopenhtml+openhtml);
var _click_left_game_list = 1;
var topopen=[];
$('#_left_game_list_previous').click(function(){
	if((_click_left_game_list-1)<1){_click_left_game_list=1;return;}	
	$('#_potint_server_'+_click_left_game_list).hide();
	_click_left_game_list--;
	$('#_potint_server_'+_click_left_game_list).show();
});
$('#_left_game_list_next').click(function(){
	if((_click_left_game_list+1)>3){_click_left_game_list=3;return;}
	$('#_potint_server_'+_click_left_game_list).hide();
	_click_left_game_list++;
	$('#_potint_server_'+_click_left_game_list).show();
});
function checkServerStat(){
	var num = 1;
	var todaynum = 44;
	var endtime = 1423583999;
	var thistime = new Date().getTime();
	thistime = parseInt(thistime/1000); // 除以1000是因为js默认到毫秒的
	var k=0;
	for(var i=1;i<num;i++){
		var opentime = $('#listnum_'+i).attr('data-value');
		opentime = parseInt(opentime-120);
		if(parseInt(thistime) > parseInt(opentime)){
			$('#listnum_'+i).removeClass('off');
			$('#listnum_'+i+' .status').text('火爆');
			var openurl = $('#listhref_'+i).attr('openurl');
			$('#listhref_'+i).attr('href',openurl);
			var topimgstr='<a href="'+topopen[k].game_web+'" target="_blank" title="97time'+topopen[k].game_name+'"><img src="http://www.97time.com/images/lgame/img_'+topopen[k].short_name+'.jpg"></a>';
			$('#kflbt >.pic').html(topimgstr);
			var topgamenamestr='<a href="'+topopen[k].game_web+'" target="_blank" title="97time'+topopen[k].game_name+'">'+topopen[k].game_name+'</a>';
			$('#topgamename').html(topgamenamestr);
			var topopendatestr = '今天 '+topopen[k].open_time;
			$('#topopendate').html(topopendatestr);
			var toplinkstr='<a href="http://www.97time.com/users/gamelogin.php?game='+topopen[k].game_id+'&server='+topopen[k].server_id+'" target="_blank" title="97time'+topopen[k].game_name+'-S'+topopen[k].server_id+'服">S'+topopen[k].server_id+'服</a><a style="margin-left:30px" href="'+topopen[k].game_web+'xsk.html" title="领取97time'+topopen[k].game_name+'礼包" target="_blank">领取礼包</a>';
			$('#toplink').html(toplinkstr);
		}
		k++;
	}
	for(var j=1;j<=todaynum;j++){
		if(parseInt(thistime) > parseInt(endtime)){
			var daval = $('#today_opt_'+j).attr('data-value');
			$('#today_opt_'+j).text(daval);
		}
	}
}
checkServerStat();  
setInterval('checkServerStat()',600000);